require('core.keymaps')
require('core.plugins')
require('core.options')
require('core.plugin_config.colors')
require('core.plugin_config.lsp-zero')
-- require('core.plugin_config.lualine')
-- require('core.plugin_config.nvim-tree')
require('core.plugin_config.neo-tree')
require('core.plugin_config.treesitter')
require('core.plugin_config.telescope')
-- require('core.plugin_config.lsp_config')
require('core.plugin_config.cmp')
require('core.plugin_config.bufferline')
require('core.plugin_config.null-ls')
